// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBAC9jBzw0v1izYGMjMf4T3fdWBgrsYak',
    appId: '1:737454600773:web:77b69dfb6285f07f27a92c',
    messagingSenderId: '737454600773',
    projectId: 'flutter-firebase-97a3f',
    authDomain: 'flutter-firebase-97a3f.firebaseapp.com',
    databaseURL:
        'https://flutter-firebase-97a3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-97a3f.appspot.com',
    measurementId: 'G-P32RKCRS3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7JBzxpu6yL5QC5gOTEOQ8sWf7-AfPWWA',
    appId: '1:737454600773:android:a9ee37608cdefc0e27a92c',
    messagingSenderId: '737454600773',
    projectId: 'flutter-firebase-97a3f',
    databaseURL:
        'https://flutter-firebase-97a3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-97a3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfgyANZ6MteQla5MPd-XMuSNrhJ6dpHCw',
    appId: '1:737454600773:ios:fa3f3ed19d00f97c27a92c',
    messagingSenderId: '737454600773',
    projectId: 'flutter-firebase-97a3f',
    databaseURL:
        'https://flutter-firebase-97a3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-97a3f.appspot.com',
    androidClientId:
        '737454600773-t02fqkumuhvmgffc7v121aja39tglhfm.apps.googleusercontent.com',
    iosClientId:
        '737454600773-t5lab1k2jgstgbehcc1qbiegqtv6vf7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebase',
  );
}
